### ISSUE TITLE
Update URL on the repo to use HTTPS

### ISSUE THREAD

**Issue by konklone** [usnationalarchives/fr2#6]
This is a tiny thing, but federalregister.gov [is a leader on HTTPS](https://18f.gsa.gov/2015/02/09/the-first-gov-domains-hardcoded-into-your-browser-as-all-https/), so you may as well have the URL on top of the repo use the `https://` protocol. Currently uses `http://`:

![image](https://cloud.githubusercontent.com/assets/4592/13242070/1907c4f4-d9bf-11e5-9402-d191340fdd2e.png)

**Comment by andrewcarpenter** [comment]
Sure thing! Thanks!

**Comment by konklone** [comment]
Thank _you_! =)
